apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager.fullname" . }}-bff
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
spec:
  type: {{ .Values.bff.service.type }}
  ports:
    - port: {{ .Values.bff.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bff
