/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tasks for the authenticated user
         * @description Returns paginated active tasks. Soft-deleted tasks are never returned.
         */
        get: operations["listTasks"];
        put?: never;
        /** Create a task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All active tasks grouped by Importance × Urgency
         * @description Returns all 9 matrix cells. No pagination. Soft-deleted tasks excluded.
         */
        get: operations["getTaskMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /**
         * Get a task by ID
         * @description Returns 404 if the task does not exist, is soft-deleted, or belongs to another user/tenant.
         */
        get: operations["getTask"];
        /**
         * Full update of a task
         * @description Replaces all mutable fields. Requires the current `version` for optimistic locking.
         */
        put: operations["updateTask"];
        post?: never;
        /**
         * Soft-delete a task
         * @description Sets `deleted_at = now()`. The database row is retained.
         *     The task disappears from all subsequent queries. Hard deletes are not supported.
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * Partial update — primarily used for state transitions
         * @description Applies partial changes. When `state` is included, the transition must be legal per
         *     the state machine in PROJECT_OVERVIEW.md §3. Illegal transitions return 422.
         *     `version` is required when `state` is present (optimistic locking).
         */
        patch: operations["patchTask"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: operations["getMyProfile"];
        /**
         * Update display name or theme
         * @description Email and authProvider are immutable and will be ignored if supplied.
         */
        put: operations["updateMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password (LOCAL users only)
         * @description Returns 400 for OAuth2 users (GOOGLE, MICROSOFT).
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate TOTP MFA enrollment
         * @description Returns a TOTP secret and otpauth URI for QR code generation.
         */
        post: operations["initiateMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm MFA enrollment with a TOTP code */
        post: operations["confirmMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disable MFA
         * @description Requires the current TOTP code to confirm identity before disabling.
         */
        delete: operations["disableMfa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new tenant */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate stats across all tenants */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated list of all users across all tenants */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Promote or demote a user role (STANDARD ↔ ADMIN) */
        patch: operations["updateUserRole"];
        trace?: never;
    };
    "/admin/reports/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export task report as xlsx or pdf */
        get: operations["exportTaskReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Legal transitions (user-driven): PLANNED→IN_PROGRESS, IN_PROGRESS→COMPLETED, OVERDUE→IN_PROGRESS.
         *     COMPLETED is terminal. OVERDUE is set only by the scheduler.
         * @enum {string}
         */
        TaskState: "PLANNED" | "IN_PROGRESS" | "COMPLETED" | "OVERDUE";
        /** @enum {string} */
        Priority: "LOW" | "MEDIUM" | "HIGH";
        /** @enum {string} */
        Theme: "LIGHT" | "DARK";
        /** @enum {string} */
        Role: "STANDARD" | "ADMIN";
        /** @enum {string} */
        AuthProvider: "LOCAL" | "GOOGLE" | "MICROSOFT";
        /** @description RFC 7807 Problem Details */
        Problem: {
            /** @description URI reference identifying the problem type */
            type?: string;
            /** @description Short, human-readable summary */
            title?: string;
            /** @description HTTP status code */
            status?: number;
            /** @description Human-readable explanation of this specific occurrence */
            detail?: string;
            /** @description URI of the resource that triggered the error */
            instance?: string;
        };
        Task: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string | null;
            state: components["schemas"]["TaskState"];
            importance: components["schemas"]["Priority"];
            urgency: components["schemas"]["Priority"];
            /**
             * Format: date
             * @description ISO 8601 date (YYYY-MM-DD)
             */
            dueDate?: string | null;
            /** @description Optimistic locking counter — include in PUT/PATCH requests */
            version: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        CreateTaskRequest: {
            title: string;
            description?: string | null;
            importance: components["schemas"]["Priority"];
            urgency: components["schemas"]["Priority"];
            /** Format: date */
            dueDate?: string | null;
        };
        /** @description Full replacement of all mutable task fields. */
        UpdateTaskRequest: {
            title: string;
            description?: string | null;
            importance: components["schemas"]["Priority"];
            urgency: components["schemas"]["Priority"];
            /** Format: date */
            dueDate?: string | null;
            /** @description Current task version — required for optimistic locking */
            version: number;
        };
        /**
         * @description Partial update. At least one field must be present.
         *     `version` is required when `state` is present.
         */
        PatchTaskRequest: {
            title?: string;
            description?: string | null;
            state?: components["schemas"]["TaskState"];
            importance?: components["schemas"]["Priority"];
            urgency?: components["schemas"]["Priority"];
            /** Format: date */
            dueDate?: string | null;
            /** @description Required when `state` is present (optimistic locking) */
            version?: number;
        };
        MatrixCell: {
            importance: components["schemas"]["Priority"];
            urgency: components["schemas"]["Priority"];
            tasks: components["schemas"]["Task"][];
        };
        TaskMatrixResponse: {
            /** @description All 9 Importance × Urgency cells (some may be empty) */
            cells: components["schemas"]["MatrixCell"][];
        };
        PagedTaskResponse: {
            data: components["schemas"]["Task"][];
            /** @description Pass as `cursor` in the next request. Absent when no more pages. */
            nextCursor?: string | null;
            /** @description Total number of matching active tasks (across all pages) */
            totalCount: number;
        };
        UserProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            displayName?: string | null;
            role: components["schemas"]["Role"];
            authProvider: components["schemas"]["AuthProvider"];
            isMfaEnabled: boolean;
            theme: components["schemas"]["Theme"];
            /**
             * @description LOCAL users only. True when the password is approaching the maximum age.
             *     Null for OAuth2 users.
             */
            passwordWarning?: boolean | null;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /** @description Only displayName and theme are mutable. email and authProvider are ignored. */
        UpdateProfileRequest: {
            displayName?: string | null;
            theme?: components["schemas"]["Theme"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        MfaEnrollResponse: {
            /** @description Base32-encoded TOTP secret for manual entry into an authenticator app */
            secret: string;
            /** @description otpauth:// URI suitable for QR code generation */
            otpauthUri: string;
        };
        MfaCodeRequest: {
            /** @description 6-digit TOTP code from the authenticator app */
            code: string;
        };
        CreateTenantRequest: {
            name: string;
        };
        Tenant: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        AdminUserItem: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName?: string | null;
            role: components["schemas"]["Role"];
            authProvider: components["schemas"]["AuthProvider"];
            /** Format: uuid */
            tenantId: string;
            /** Format: date-time */
            createdAt: string;
        };
        PagedUserResponse: {
            data: components["schemas"]["AdminUserItem"][];
            nextCursor?: string | null;
            totalCount: number;
        };
        UpdateRoleRequest: {
            role: components["schemas"]["Role"];
        };
        AdminStats: {
            totalTenants: number;
            totalUsers: number;
            /** @description Count of active (non-deleted) tasks */
            totalTasks: number;
            /** @description Active task count per state (e.g. {"PLANNED":42,"IN_PROGRESS":10,...}) */
            tasksByState: {
                [key: string]: number;
            };
        };
    };
    responses: {
        /** @description Validation error (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Insufficient role — ADMIN required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found, soft-deleted, or belongs to another tenant/user */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Optimistic lock version mismatch or unique constraint violation */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Illegal state transition */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Task UUID */
        TaskId: string;
        /** @description User UUID */
        UserId: string;
        /** @description Opaque pagination cursor from a previous response */
        Cursor: string;
        /** @description Maximum number of results to return (1–100) */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTasks: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of results to return (1–100) */
                limit?: components["parameters"]["Limit"];
                state?: components["schemas"]["TaskState"];
                importance?: components["schemas"]["Priority"];
                urgency?: components["schemas"]["Priority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTaskResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTaskMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task matrix */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskMatrixResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    patchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    initiateMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrollResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    confirmMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description MFA enabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    disableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description MFA disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of results to return (1–100) */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated user list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Role updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    exportTaskReport: {
        parameters: {
            query: {
                /** @description Scope report to a specific tenant. Omit for all tenants. */
                tenantId?: string;
                format: "xlsx" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
